### ISSUE TITLE
Incorrect weight 

### ISSUE THREAD

**Issue by whatsthecraic** [the-data-lab/GraphOne#7] opened 2019-11-21 12:07 UTC
Hi there,
while using the static_view, the library doesn't return the last value set for a weight of a given edge, when the edge has been first inserted, then deleted, and finally inserted again. For instance, given the sequence:

```
insert_edge(v0, v1, 102);
insert_edge(v0, v2, 103);
create_snapshot();
delete_edge(v0, v2)
create_snapshot();
insert_edge(v0, v2, 1010);
create_snapshot();
```

The edges returned for the vertex v0 are <v0, v1, 102> and <v0, v2, 103>, instead of <v0, v2, 1010>.
See repro: https://gist.github.com/whatsthecraic/63400a1aa04562021d9f6fa5656110f5

**Comment by pradeep-k** [comment] 2019-11-25 22:41
Thanks for providing the testcase. I will test it and provide you further information.  GraphOne is supposed to provide correct weight. I will check where the bug is.

**Comment by whatsthecraic** [comment] 2019-11-26 14:29
Hi @pradeep-k ,
Note that the above snippet even after a deletion, in the undirected graph:

insert_edge(v0, v1, 102);
insert_edge(v0, v2, 103);
create_snapshot();
delete_edge(v0, v2)
create_snapshot();

the only edge retrieved for v0 is <v0, v2, 103> instead of <v0, v2, 102>. 

Besides that, I don't get the meaning of the parameter simple in create_static_view. I thought with simple=false, it would return an array with all insertions/deletions performed, in the example above a list of length = 3 for v0 with the content [ insert_edge(v0, v1, 102), insert_edge(v0, v2, 103), delete_edge(v0, v2)], while right now it behaves like simple = true?

**Comment by pradeep-k** [comment] 2019-11-26 17:54
Thanks for the feedback. I am able to reproduce the issue, can can confirm that it is a bug. I will update you when the bug is fixed. 

I will update the documents on all the 3 flags of the view, and will inform you when the document is updated.

**Comment by pradeep-k** [comment] 2019-11-27 20:06
The bug is fixed. See the commit 316b043b8ef69f0df7b6bd1d1bb40df7e0cf3081

The documentation part is pending.

**Comment by whatsthecraic** [comment] 2019-11-28 12:59
Hi @pradeep-k ,even with this patch, in my test the deletion is still ignored, see comment above. Is this a different issue?

**Comment by pradeep-k** [comment] 2019-11-28 13:49
It works on a testcase adopted from your code snippet:
```
pkumar@mira:~/GraphOne/build$ ./graphone32 -j 40 -v 3
Global vcount = 3
Threads Count = 19
insert 0 - 1: 102
insert 0 - 2: 103
Vertex count: 3
[vertex_id: 0]
2    outgoing edges: 1 [w=102], 2 [w=103]
[vertex_id: 1]
1    outgoing edges: 0 [w=102]
[vertex_id: 2]
1    outgoing edges: 0 [w=103]
remove 0 - 2: 104
Vertex count: 3
[vertex_id: 0]
1    outgoing edges: 1 [w=102]
[vertex_id: 1]
1    outgoing edges: 0 [w=102]
[vertex_id: 2]
0    outgoing edges:
insert 0 - 2: 1010
Vertex count: 3
[vertex_id: 0]
2    outgoing edges: 1 [w=102], 2 [w=1010]
[vertex_id: 1]
1    outgoing edges: 0 [w=102]
[vertex_id: 2]
1    outgoing edges: 0 [w=1010]
```

See the test_user1() function in the plaingraph_test.h, and dump() function in plain_to_edge.h. 
Do you have a new testcase? Kindly share, if so.

**Comment by whatsthecraic** [comment] 2019-11-28 16:30
It crashes with the following snippet: https://gist.github.com/whatsthecraic/fcc9dfd9ea8fac9c16faaecf86536bdf
```
clang++ -std=c++17 -DOVER_COMMIT -DDEL -DTBB -DPLAIN_GRAPH -DB64 -I/home/dean/workspace/graphone/src -I/home/dean/workspace/graphone/gview -I/home/dean/workspace/graphone/include -I/home/dean/workspace/graphone/onedata -I/home/dean/workspace/graphone/analytics -O0 -g3 -fno-limit-debug-info -Wall -fmessage-length=0 -fopenmp -pthread -o "helloworld"  ../hello_graphone.cpp  /home/dean/workspace/graphone/build/src/libsrc64.a /home/dean/workspace/graphone/build/onedata/libonedata64.a -ltbb
```
The crash is at the dump following `remove 7 -> 5`. It's a memory corruption, there's useful no backtrace.

**Comment by pradeep-k** [comment] 2019-11-28 21:40
I have fixed the memory corruption bug. It was introduced by last fix. Thank you very much for the testcase.  I will be submitting the code shortly. Here is the output of your testcase:
```
>> add 7 -> 3 [7003]                                                                                                                               [197/1997]
>> add 4 -> 2 [4002]
>> add 7 -> 5 [7005]
>> add 5 -> 1 [5001]
>> add 5 -> 3 [5003]
>> add 7 -> 1 [7001]
>> add 3 -> 1 [3001]
>> add 6 -> 4 [6004]
>> add 6 -> 2 [6002]
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  3 outgoing edges: 1 [w=7003], 4 [w=7005], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  1 outgoing edges: 3 [w=4002]
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  2 incoming edges: 2 [w=4002], 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  1 incoming edges: 0 [w=7005]
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 1 -> 3
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  3 outgoing edges: 1 [w=7003], 4 [w=7005], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  1 outgoing edges: 3 [w=4002]
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  2 incoming edges: 2 [w=4002], 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  1 incoming edges: 0 [w=7005]
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]                                                                                                                            [145/1997]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 4 -> 6
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  3 outgoing edges: 1 [w=7003], 4 [w=7005], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  1 outgoing edges: 3 [w=4002]
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  2 incoming edges: 2 [w=4002], 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  1 incoming edges: 0 [w=7005]
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 1 -> 7
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  3 outgoing edges: 1 [w=7003], 4 [w=7005], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  1 outgoing edges: 3 [w=4002]
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  2 incoming edges: 2 [w=4002], 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  1 incoming edges: 0 [w=7005]
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:
>> remove 7 -> 5                                                                                                                                    [93/1997]
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  1 outgoing edges: 3 [w=4002]
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  2 incoming edges: 2 [w=4002], 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 4 -> 2
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  0 outgoing edges:
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  1 incoming edges: 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 3 -> 5
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:                                                                                                                                 [41/1997]
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  0 outgoing edges:
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  1 incoming edges: 6 [w=6002]
[vertex_id: 4, name: 5]
  2 outgoing edges: 5 [w=5001], 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  3 incoming edges: 4 [w=5001], 0 [w=7001], 1 [w=3001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 5 -> 1
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  0 outgoing edges:
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  1 incoming edges: 6 [w=6002]
[vertex_id: 4, name: 5]
  1 outgoing edges: 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  2 incoming edges: 1 [w=3001], 0 [w=7001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 3 -> 7
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  0 outgoing edges:
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  1 incoming edges: 6 [w=6002]
[vertex_id: 4, name: 5]
  1 outgoing edges: 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  2 incoming edges: 1 [w=3001], 0 [w=7001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:

>> remove 2 -> 6
<-- DUMP --> Vertex count: 4096
[vertex_id: 0, name: 7]
  2 outgoing edges: 1 [w=7003], 5 [w=7001]
  0 incoming edges:
[vertex_id: 1, name: 3]
  1 outgoing edges: 5 [w=3001]
  2 incoming edges: 0 [w=7003], 4 [w=5003]
[vertex_id: 2, name: 4]
  0 outgoing edges:
  1 incoming edges: 6 [w=6004]
[vertex_id: 3, name: 2]
  0 outgoing edges:
  1 incoming edges: 6 [w=6002]
[vertex_id: 4, name: 5]
  1 outgoing edges: 1 [w=5003]
  0 incoming edges:
[vertex_id: 5, name: 1]
  0 outgoing edges:
  2 incoming edges: 1 [w=3001], 0 [w=7001]
[vertex_id: 6, name: 6]
  2 outgoing edges: 2 [w=6004], 3 [w=6002]
  0 incoming edges:
```

I also tested with undirected graphs. It looks good.

**Comment by pradeep-k** [comment] 2019-11-28 21:51
Commit number is https://github.com/the-data-lab/GraphOne/commit/b9bb2267e277ee8e413c5343b0606d5dffa92471

**Comment by pradeep-k** [comment] 2019-11-29 06:10
It is also interesting that the testcase adds 3 ->1 as an edge but tries to delete 1->3. Similar are the other edges. That is why, the final result does not have 0 edges. When I correct the direction, the final printed dump() does not have any edges. 

GraphOne is designed for analytics purpose, where we assume that the data is coming from a source who already have verified integrity of the data. Therefore we do not check the integrity of the data, and invalid deleted data may get dropped during archiving. For example, input of OLAP analytics (data warehouse) always came from OLTP databases.   So our assumption is valid for anaylytics purpose.

**Comment by pradeep-k** [comment] 2019-11-29 06:18
simple, private and stale flag implementation is complete.  The commit number is 088afe61ce35d6cc12285da6b728cbce9342d658

README will be updated shortly for their actual meanings.

**Comment by whatsthecraic** [comment] 2019-12-02 16:31
Hi @pradeep-k 

Thanks for the fixes. Though I'm still struggling with the API. See the attached files: https://gist.github.com/whatsthecraic/01cbc290cffa5bc348596563b709381a 

I still don't get the difference between STALE and SIMPLE. I thought that STALE are the changes until the last snapshot/archiving, while SIMPLE are supposed to be the changes until the last update. In the test above STALE returns nothing, while SIMPLE pollutes the adjacency list with some empty edges.

Finally, there must be some kind of race condition or so when invoking the method g->wait_for_archive(). In my case, the above repro completely hangs once every ten invocations or so.

**Comment by pradeep-k** [comment] 2019-12-02 17:34
The testcase that you provided worked in my system. The tests were performed by creating a new repository from github. It looks like a correct answer. No hang, immediate execution was observed.
```
pkumar@mira:~/src/GraphOne/del$ ./graphone64
<-- DUMP --> Vertex count: 32
[vertex_id: 0, name: 2]
  2 outgoing edges: 1 [w=0.9], 2 [w=0.69]
  2 incoming edges: 1 [w=0.9], 2 [w=0.69]
[vertex_id: 1, name: 3]
  4 outgoing edges: 0 [w=0.9], 2 [w=0.13], 3 [w=0.5], 6 [w=0.32]
  4 incoming edges: 0 [w=0.9], 2 [w=0.13], 3 [w=0.5], 6 [w=0.32]
[vertex_id: 2, name: 4]
  2 outgoing edges: 0 [w=0.69], 1 [w=0.13]
  2 incoming edges: 0 [w=0.69], 1 [w=0.13]
[vertex_id: 3, name: 5]
  3 outgoing edges: 1 [w=0.5], 4 [w=0.63], 6 [w=0.12]
  3 incoming edges: 1 [w=0.5], 4 [w=0.63], 6 [w=0.12]
[vertex_id: 4, name: 6]
  5 outgoing edges: 3 [w=0.63], 5 [w=0.53], 6 [w=0.64], 7 [w=0.23], 8 [w=0.63]
  5 incoming edges: 3 [w=0.63], 5 [w=0.53], 6 [w=0.64], 7 [w=0.23], 8 [w=0.63]
[vertex_id: 5, name: 7]
  2 outgoing edges: 4 [w=0.53], 7 [w=0.36]
  2 incoming edges: 4 [w=0.53], 7 [w=0.36]
[vertex_id: 6, name: 8]
  3 outgoing edges: 1 [w=0.32], 3 [w=0.12], 4 [w=0.64]
  3 incoming edges: 1 [w=0.32], 3 [w=0.12], 4 [w=0.64]
[vertex_id: 7, name: 9]
  2 outgoing edges: 4 [w=0.23], 5 [w=0.36]
  2 incoming edges: 4 [w=0.23], 5 [w=0.36]
[vertex_id: 8, name: 10]
  1 outgoing edges: 4 [w=0.63]
  1 incoming edges: 4 [w=0.63]
0 non archived edges:
```

**Comment by pradeep-k** [comment] 2019-12-02 17:35
>>I still don't get the difference between STALE and SIMPLE. I thought that STALE are the changes until the last snapshot/archiving, while SIMPLE are supposed to be the changes until the last update.

You are fully correct here.  It should behave that way as per my testing.

**Comment by pradeep-k** [comment] 2019-12-02 17:42
Steps to reproduction:
- copy the repro.cpp from the url. Rename it to main.cpp
- Enable with debug flag in CMakeLists.txt 
- mkdir build
- cmake ../
- make graphone64
- ./graphone64  

Using gdb will print all the symbols in stack trace.

If you need more clarification, we can set up a meeting call, so that you don't need to waste a lot of time on debugging.

**Comment by whatsthecraic** [comment] 2019-12-03 11:49
ouch, I didn't pick the latest changes from upstream on this computer. I confirm it works for me as well.

Note that the compiler issues a warning here:
```
static_view.h:213:
        realloc(edges, edge_count*sizeof(edgeT_t<T>));
```

realloc may return a new pointer if it cannot expand the given buffer.

**Comment by pradeep-k** [comment] 2019-12-04 15:12
Thank you very much for confirming the fix. I also fixed the warning. 

I am closing the bug now. However, feel free to file a new issue if you have any other problems.

**Closed by pradeep-k** 2019-12-04 15:12 UTC
